[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Load .env so $RPC_URL is available in rpc_endpoints
[rpc_endpoints]
sepolia = "${RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
